'use strict';
const assert=require('node:assert/strict'),B=require('../assets/js/bess.js'),F=require('../assets/js/finance.js'),fixture=require('./bess-fixture');
let passed=0;const check=(name,ok)=>{assert(ok,name);passed++;console.log('  ✓ '+name);};
const solar=F.compute({capacity:7,genFactor:1460,costPerKwp:90000,tariff:15}),calc=patch=>B.compute({...fixture,...patch},solar),close=(a,b)=>Math.abs(a-b)<1e-8;
check('old proposals default to no battery',!B.enabled({})&&!B.DEFAULTS.bessEnabled);
check('strict enabled parsing never treats the string no/false as Yes',!B.enabled({bessEnabled:'no'})&&!B.enabled({bessEnabled:'false'})&&B.enabled({bessEnabled:'yes'}));
check('default ratings and economics are blank, not fabricated',Object.entries(B.DEFAULTS).filter(([k])=>k!=='bessPowerDerate'&&/Capacity|Dod|Eff|Power|Load|Cost|Reserve|Rte|Days|Cycles|Rate|Om|Life/.test(k)).every(([,v])=>v===''));
const off=calc({bessEnabled:false});check('No suppresses stored financial and backup output',!off.enabled&&off.cost===null&&off.annualBenefit===null&&off.backupHours===null&&off.errors.length===0);
const blank=B.compute({...B.DEFAULTS,bessEnabled:true},solar);check('Yes alone has no invented backup, price or savings',blank.capacity===null&&blank.backupHours===null&&blank.cost===null&&blank.annualBenefit===null);
const b=calc({});check('usable DC and AC energy keep kWh separate from kW',close(b.usableDc,9)&&close(b.usableAc,8.55)&&b.power===5);
check('full-charge runtime respects discharge efficiency',close(b.backupHours,4.275));
check('reserve-only runtime uses reserved usable energy',close(b.reserveHours,.855));
check('separate installed price adds only to indicative combined investment',b.cost===300000&&b.combined===solar.netInvestment+300000);
check('daily AC shifting is bounded by usable capacity and reserve',close(b.dailyDelivered,6.84));
check('annual energy is daily energy times entered operating days',close(b.annualDelivered,2052));
check('net benefit subtracts charging opportunity cost and O&M',close(b.annualValue,30780)&&close(b.annualChargingCost,6840)&&close(b.annualBenefit,21940));
check('simple storage payback can exceed entered life without promising recovery',b.payback>b.life&&close(b.payback,300000/21940));
check('missing continuous power withholds reserve as well as full-charge runtime',calc({bessPower:''}).reserveHours===null&&calc({bessPower:''}).backupHours===null);
check('reserve runtime remains technical even when a tariff is missing',close(calc({bessImportRate:''}).reserveHours,.855));
check('blank whitespace and boolean numeric fields are not assumed zero or one',calc({bessCost:' '}).cost===null&&calc({bessPower:true}).power===null);
check('inverter compatibility pending suppresses backup',calc({bessBackupReady:'pending'}).backupHours===null);
check('no backup scope suppresses backup',calc({bessBackupReady:'no'}).backupHours===null);
check('architecture pending suppresses backup',calc({bessCoupling:'pending'}).backupHours===null);
check('inverter model missing suppresses backup',calc({bessInverter:''}).backupHours===null);
check('load over continuous power is rejected',calc({bessLoad:'6'}).overloaded&&calc({bessLoad:'6'}).backupHours===null);
check('exact power limit permits backup',close(calc({bessLoad:'5'}).backupHours,1.71));
check('zero and missing load never fabricate runtime',calc({bessLoad:'0'}).backupHours===null&&calc({bessLoad:''}).backupHours===null);
check('backup-first mode makes no bill-savings claim',calc({bessUseCase:'backup'}).annualBenefit===null&&calc({bessUseCase:'backup'}).backupHours>0);
check('small daily charge availability caps energy including RTE',close(calc({bessSourceEnergy:'1'}).dailyDelivered,.9));
check('selected demand caps AC delivery',close(calc({bessDemand:'1'}).dailyDelivered,1));
check('charging power × window × RTE caps output',close(calc({bessChargePower:'.1',bessChargeHours:'1'}).dailyDelivered,.09));
check('discharge power × window caps output',close(calc({bessDischargeHours:'.1'}).dailyDelivered,.5));
check('low cycle allowance caps output',close(calc({bessCycles:'.1'}).dailyDelivered,.684));
check('100 percent reserve leaves no daily shifting',calc({bessReserve:'100'}).dailyDelivered===0);
check('zero days is invalid rather than divide-by-zero',calc({bessDays:'0'}).annualBenefit===null);
check('overlapping daily duration is invalid',calc({bessChargeHours:'20',bessDischargeHours:'10'}).annualBenefit===null);
check('RTE cannot exceed discharge efficiency',calc({bessRte:'99'}).annualBenefit===null);
check('self-consumption cannot exceed annual solar generation',close(B.compute(fixture,{annualGen:300,netInvestment:100}).annualDelivered,270));
check('TOU shifting is not incorrectly bounded by PV generation',B.compute({...fixture,bessUseCase:'tou'},{annualGen:0,netInvestment:100}).annualDelivered>0);
check('no solar generation means no solar charging benefit',B.compute(fixture,{annualGen:0,netInvestment:100}).annualDelivered===0);
check('favourable export credit can make storage uneconomic',calc({bessSourceRate:'15'}).annualBenefit<0&&calc({bessSourceRate:'15'}).payback===null);
check('zero source tariff is explicit and valid',close(calc({bessSourceRate:'0'}).annualBenefit,28780));
check('zero or negative annual benefit never becomes a positive payback',calc({bessImportRate:'0'}).payback===null&&calc({bessImportRate:'0',bessSourceRate:'0',bessOm:'0'}).payback===null);
check('missing capex shows no payback or combined price',calc({bessCost:''}).payback===null&&calc({bessCost:''}).combined===null);
check('negative storage cost is rejected',calc({bessCost:'-1'}).cost===null&&calc({bessCost:'-1'}).errors.length>0);
for(const key of ['bessCapacity','bessDod','bessDischargeEff','bessPower','bessReserve','bessRte','bessCycles','bessDays','bessSourceEnergy','bessDemand','bessChargePower','bessChargeHours','bessDischargeHours','bessImportRate','bessSourceRate','bessOm','bessLife'])check('missing '+key+' blocks economics',calc({[key]:''}).annualBenefit===null);
for(const [key,value] of [['bessDod','101'],['bessReserve','-1'],['bessDischargeEff','0'],['bessRte','0'],['bessDays','367'],['bessLife','31'],['bessCycles','5'],['bessChargeHours','25'],['bessOm','-100']])check('invalid '+key+' is flagged',calc({[key]:value}).annualBenefit===null&&calc({[key]:value}).errors.length>0);
check('NaN and Infinity inputs do not leak into output',calc({bessCapacity:'Infinity'}).usableDc===null&&calc({bessCost:'NaN'}).cost===null);
const huge=calc({bessImportRate:'1e308'});check('arithmetic overflow is rejected',huge.annualBenefit===null&&huge.errors.some(x=>x.includes('too large')));
const before=JSON.stringify(F.compute({capacity:7,genFactor:1460,costPerKwp:90000,tariff:15}));check('BESS inputs do not change the approved solar Finance results',before===JSON.stringify(F.compute({capacity:7,genFactor:1460,costPerKwp:90000,tariff:15,...fixture})));
console.log(`\n${passed} passed, 0 failed`);
