/* Branding, non-duplicated customer journey and honest engineering requests. */
'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {execFileSync} = require('node:child_process');
const puppeteer = require('puppeteer-core');
let passed=0;
function check(name,ok){assert(ok,name);passed++;console.log('  ✓ '+name);}
(async()=>{
  const root=path.join(__dirname,'..');
  const cover=fs.readFileSync(path.join(root,'assets/ktm-cover-page-1.png'));
  check('original approved cover remains unchanged',crypto.createHash('sha256').update(cover).digest('hex')==='0d8e226e919f215b2ecd4ac17c57278da6841922322455c0ccb49c11a7876961');
  const crop=execFileSync('convert',[path.join(root,'assets/ktm-cover-page-1.png'),'-crop','304x180+62+62','+repage','-depth','8','rgb:-']);
  const logo=execFileSync('convert',[path.join(root,'assets/images/ktm-cover-logo.png'),'-depth','8','rgb:-']);
  check('new logo is an exact pixel crop, not a recreation',crop.equals(logo));
  const {upgradeProposalContent,CONTENT}=require('../assets/js/content.js');
  const legacy={pageClosing:{cta:'Call us today for a free site survey:'},pageSolution:{sub:'Designed Specifically for Your Property'},custom:'My individually negotiated wording'};
  const migrated=upgradeProposalContent(legacy);
  check('legacy default copy upgrades in saved proposals',migrated.pageClosing.cta===CONTENT.pageClosing.cta && migrated.pageSolution.sub===CONTENT.pageSolution.sub);
  check('custom copy and original stored object are not overwritten',migrated.custom===legacy.custom && legacy.pageClosing.cta==='Call us today for a free site survey:');
  const {default:chromium}=await import('@sparticuz/chromium');
  const browser=await puppeteer.launch({executablePath:process.env.CHROMIUM_PATH||await chromium.executablePath(),args:chromium.args,headless:true});
  try {
    const base=process.env.QA_BASE||'http://127.0.0.1:8080';
    const page=await browser.newPage();const errors=[];
    page.on('pageerror',e=>errors.push(e.message));
    await page.setViewport({width:1440,height:1100});
    await page.goto(base+'/quotation.html',{waitUntil:'networkidle0'});
    await page.evaluate(()=>document.fonts.ready);
    check('all inner-page and closing logos use the approved asset',await page.$$eval('.page:not(#pageCover)',els=>els.every(e=>e.querySelector('.pg-logo img,.closing-brand img')?.getAttribute('src')==='assets/images/ktm-cover-logo.png')));
    check('logos fit within their header',await page.$$eval('.pg-head',els=>els.every(e=>e.querySelector('img').getBoundingClientRect().height<=e.getBoundingClientRect().height)));
    check('old logo override control cannot split the brand',await page.$('#logoUpload')===null);
    await page.$eval('#formLogo',e=>e.src='assets/images/logo.png');
    await page.evaluate(()=>Render.renderAll());
    check('render restores one canonical identity',await page.$eval('#formLogo',e=>e.getAttribute('src')==='assets/images/ktm-cover-logo.png'));
    check('repeated savings and phone CTA blocks removed',await page.evaluate(()=>['v_wsHighlight','v_wsAnnualGen','v_wsAnnualSaving','v_wsLifetimeSaving','v_clHighlight','v_clCtaPhone'].every(id=>!document.getElementById(id))));
    check('builder keeps one paper acceptance block',await page.$$eval('.accept-block',els=>els.length===1));
    // Capture a page header to visually verify the extracted mark at print size.
    fs.mkdirSync(path.join(__dirname,'shots'),{recursive:true});
    const proof=await browser.newPage();await proof.setViewport({width:820,height:1130});
    const markup=await page.$eval('#pageExec',e=>e.outerHTML);
    await proof.setContent('<base href="'+page.url()+'"><link rel="stylesheet" href="assets/css/app.css">'+markup);
    await proof.evaluate(()=>document.fonts.ready);
    await proof.waitForFunction(()=>[...document.images].every(i=>i.complete));
    await proof.$eval('.page',e=>e.style.transform='none');
    await (await proof.$('.page')).screenshot({path:path.join(__dirname,'shots/approved-logo-page.png')});
    await proof.close();
    const id=await page.evaluate(legacy=>Proposals.create({...StateStore.DEFAULTS,custName:'Engineering Review Customer',custAddress:'Baner, Pune',propRef:'ENG-007',propDate:'2099-01-01',companyPhone:'9309486769'},{content:legacy}).id,legacy);
    const view=await browser.newPage();view.on('pageerror',e=>errors.push(e.message));
    await view.setViewport({width:1200,height:1100});
    await view.goto(base+'/share.html?p='+id,{waitUntil:'networkidle0'});
    check('customer header uses same identity',await view.$eval('#shareLogo',e=>e.getAttribute('src')==='assets/images/ktm-cover-logo.png'));
    check('one action hub placed after the full proposal',await view.evaluate(()=>document.querySelectorAll('#shareAcceptWrap').length===1 && !!(document.getElementById('sharePages').compareDocumentPosition(document.getElementById('shareAcceptWrap')) & Node.DOCUMENT_POSITION_FOLLOWING)));
    check('engineering controls owned by the single hub',await view.$eval('#shareSimBar',e=>!!e.closest('#shareAcceptWrap')));
    check('online paper signature is not duplicated',!await view.$eval('#pageClosing .accept-block',e=>e.checkVisibility()));
    check('acknowledgement is optional, collapsed by default',!await view.$eval('#localAcknowledgement',e=>e.open));
    check('still-reviewing stage cannot prepare request',await view.$eval('#prepareRequest',e=>e.disabled));
    await view.$eval('#engineeringRequestForm',e=>e.dispatchEvent(new Event('submit',{cancelable:true,bubbles:true})));
    check('bypassing disabled button still enforces interest',await view.$eval('#requestError',e=>e.textContent.includes('confirm your interest')));
    await view.select('#requestStage','interested');
    await view.$eval('#requestSurvey',e=>{e.checked=false;e.dispatchEvent(new Event('change',{bubbles:true}));});
    await view.click('#prepareRequest');
    check('empty service choice rejected',await view.$eval('#requestError',e=>e.textContent.includes('at least one')));
    await view.click('#requestArka');await view.click('#requestPvsyst');
    await view.$eval('#requestLocation',e=>{e.value='   ';e.dispatchEvent(new Event('input',{bubbles:true}));});
    await view.click('#prepareRequest');
    check('whitespace-only site address rejected',await view.$eval('#requestError',e=>e.textContent.includes('site address')));
    await view.$eval('#requestLocation',e=>{e.value='Baner roof, Pune';e.dispatchEvent(new Event('input',{bubbles:true}));});
    await view.type('#requestWindow','Saturday morning');
    const before=await view.evaluate(id=>JSON.stringify(Proposals.get(id)),id);
    await view.click('#prepareRequest');
    const message=await view.$eval('#requestMessage',e=>e.value);
    check('message includes proposal reference, site, selected services and timing',['ENG-007','Baner roof, Pune','Arka 3D layout','PVsyst simulation report','Saturday morning'].every(text=>message.includes(text)));
    check('unselected site survey not inserted',!message.includes('Requested: Site survey'));
    check('request never pretends an order is placed',message.includes('not an installation order') && message.includes('any fees'));
    check('request preparation does not change saved proposal/order status',await view.evaluate(({id,before})=>JSON.stringify(Proposals.get(id))===before,{id,before}));
    check('WhatsApp contains exactly the reviewed message',await view.$eval('#requestWhatsApp',(e,message)=>new URL(e.href).searchParams.get('text')===message,message));
    check('delivery status honestly says not sent',await view.$eval('#requestDeliveryNote',e=>e.textContent.includes('not sent or booked')));
    // Clipboard fallback is explicit, not an invented success.
    await view.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied');}}}));
    await view.click('#copyRequest');
    check('clipboard denial offers manual copy',await view.$eval('#requestDeliveryNote',e=>e.textContent.includes('Automatic copy is unavailable')));
    await view.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async text=>{window.__copied=text;}}}));
    await view.click('#copyRequest');
    check('clipboard success copies exact message',await view.evaluate(message=>window.__copied===message,message));
    await view.type('#requestWindow',' after 10am');
    check('editing request invalidates old message and old WhatsApp URL',await view.evaluate(()=>document.getElementById('requestPreview').hidden && !document.getElementById('requestWhatsApp').hasAttribute('href')));
    await view.select('#requestStage','reviewing');
    check('returning to review disables sending',await view.$eval('#prepareRequest',e=>e.disabled));
    // Add one report; it should appear once online, never as a duplicate request.
    await view.evaluate(id=>{const b=Proposals.get(id);b.form.arkaUrl='https://example.com/layout';Proposals.put(b);},id);
    await view.reload({waitUntil:'networkidle0'});
    check('provided report cannot be requested again',await view.$eval('#requestArka',e=>e.disabled));
    check('only missing report remains selectable',!await view.$eval('#requestPvsyst',e=>e.disabled));
    check('provided report link visible exactly once online',await view.$$eval('a[href="https://example.com/layout"]',els=>els.filter(e=>e.checkVisibility()).length===1));
    await view.emulateMediaType('print');
    check('print restores report reference in its technical page',await view.$eval('#v_tsRefsWrap',e=>e.checkVisibility()));
    check('print restores paper signature',await view.$eval('#pageClosing .accept-block',e=>e.checkVisibility()));
    check('print excludes online request hub',!await view.$eval('#shareAcceptWrap',e=>e.checkVisibility()));
    await view.emulateMediaType('screen');
    const cloneResult=await view.evaluate(async()=>{
      const result={};
      const canvas=await html2canvas(document.getElementById('pageClosing'),{scale:1,logging:false,onclone:doc=>{
        doc.body.classList.add('qs-pdf-capture');
        result.signature=doc.defaultView.getComputedStyle(doc.querySelector('#pageClosing .accept-block')).display!=='none';
        result.references=doc.defaultView.getComputedStyle(doc.getElementById('v_tsRefsWrap')).display!=='none';
        result.logo=doc.querySelector('#pageClosing .closing-brand img').getAttribute('src');
      }});result.size=[canvas.width,canvas.height];return result;
    });
    check('PDF clone restores signatures and report references',cloneResult.signature && cloneResult.references);
    check('PDF uses approved closing logo',cloneResult.logo==='assets/images/ktm-cover-logo.png' && cloneResult.size[1]>1000);
    // Small screens, invalid contacts and unavailable report URLs.
    await view.evaluate(id=>{const b=Proposals.get(id);b.form.companyPhone='unavailable';b.form.arkaUrl='javascript:alert(1)';Proposals.put(b);},id);
    await view.reload({waitUntil:'networkidle0'});
    check('unsafe URL is not exposed in technical reference or hub',await view.$$eval('a',els=>els.every(e=>!e.href.startsWith('javascript:'))));
    await view.select('#requestStage','ready');await view.click('#prepareRequest');
    check('invalid contact offers copy, not invented WhatsApp destination',await view.$eval('#requestWhatsApp',e=>!e.checkVisibility() && !e.hasAttribute('href')));
    check('copy-only fallback explains nothing was sent',await view.$eval('#requestDeliveryNote',e=>e.textContent.includes('No valid WhatsApp')));
    await view.setViewport({width:390,height:844});
    check('hub fits mobile screen without horizontal overflow',await view.$eval('#shareAcceptWrap',e=>e.getBoundingClientRect().right<=innerWidth && e.scrollWidth<=e.clientWidth+1));
    await view.$eval('#shareAcceptWrap',e=>e.scrollIntoView());
    await view.screenshot({path:path.join(__dirname,'shots/engineering-mobile.png'),fullPage:false});
    await view.setViewport({width:1200,height:1100});
    await view.addStyleTag({content:'.share-topbar{position:static!important}'});
    await (await view.$('#shareAcceptWrap')).screenshot({path:path.join(__dirname,'shots/engineering-hub.png')});
    check('no runtime errors',errors.length===0);
    console.log(`\n${passed} passed, 0 failed`);
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
