'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright'),pkg=require('@sparticuz/chromium');
(async()=>{const b=await chromium.launch({executablePath:await(pkg.default||pkg).executablePath(),args:(pkg.default||pkg).args.filter(a=>a!=='--single-process'),headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1100}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.QA_BASE||'http://127.0.0.1:8080')+'/quotation.html');await p.waitForFunction(()=>window.Render?.lastState&&document.querySelector('.studio-ready'));await p.evaluate(()=>document.fonts.ready);
 await p.evaluate(()=>{document.getElementById('advancedWrap').open=true;document.querySelector('[data-section="tiltDeg"]').open=true;});
 const before=await p.evaluate(()=>({form:JSON.stringify(StateStore.collectForm()),page:pageTechSpec.innerHTML}));
 const review=p.locator('.eng-basis .eng-group').first();await review.locator('summary').focus();await review.locator('summary').press('Enter');assert.equal(await review.evaluate(e=>e.open),true);
 for(const width of [1440,390]){await p.setViewportSize({width,height:1100});const data=await p.evaluate(()=>{const group=document.querySelector('.eng-basis'),items=[...engineeringReview.querySelectorAll('li')];return {fits:group.scrollWidth<=group.clientWidth+2,items:items.length,copySizes:items.map(e=>parseFloat(getComputedStyle(e.querySelector('p')||e).fontSize)),summarySizes:[...group.querySelectorAll('.eng-group>summary>span')].map(e=>parseFloat(getComputedStyle(e).fontSize)),titles:group.querySelectorAll('.eng-group>summary>small').length,overflow:items.some(e=>e.scrollWidth>e.clientWidth+1)};});assert.ok(data.fits&&!data.overflow);assert.ok(data.items>0);assert.ok(data.copySizes.every(n=>n>=10&&n<=12));assert.ok(data.summarySizes.every(n=>n>=11&&n<=13));assert.equal(data.titles,6);}
 await p.setViewportSize({width:1440,height:1500});await p.locator('.eng-basis').scrollIntoViewIfNeeded();const shots=path.join(__dirname,'shots','engineering-panel');fs.mkdirSync(shots,{recursive:true});await p.locator('.eng-basis').screenshot({path:path.join(shots,'advanced.png')});
 await review.locator('summary').focus();await review.locator('summary').press('Enter');assert.equal(await review.evaluate(e=>e.open),false);const after=await p.evaluate(()=>({form:JSON.stringify(StateStore.collectForm()),page:pageTechSpec.innerHTML}));assert.deepEqual(after,before);assert.deepEqual(errors,[]);
 console.log('PASS: compact engineering typography, six styled groups, severity notices, desktop/mobile fit, keyboard toggles and unchanged form/PDF markup.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
