'use strict';
const assert=require('node:assert/strict'),{chromium}=require('playwright'),pkg=require('@sparticuz/chromium');
(async()=>{const browser=await chromium.launch({executablePath:await(pkg.default||pkg).executablePath(),args:(pkg.default||pkg).args.filter(a=>a!=='--single-process'),headless:true});try{
 const base=process.env.QA_BASE||'http://127.0.0.1:8080',p=await browser.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(base+'/quotation.html');await p.waitForFunction(()=>window.Render?.lastState);
 await p.selectOption('#pdfFormat','power');assert.equal(await p.locator('#downloadLabel').textContent(),'Download Power Proposal (6 Pages)');assert.match(await p.locator('#pdfFormat option:checked').textContent(),/6-page/);
 await p.evaluate(()=>{StateStore.applyForm({systemEnabled:true,systemTemplate:'custom',systemName:'Test EV system'});Render.renderAll();});await p.selectOption('#pdfFormat','system-power');assert.match(await p.locator('#downloadLabel').textContent(),/\(1 Page\)$/);await p.selectOption('#pdfFormat','system');assert.match(await p.locator('#downloadLabel').textContent(),/\(2 Pages\)$/);
 await p.selectOption('#pdfFormat','full');const fullCount=await p.evaluate(()=>Render.lastVisible.length);assert.match(await p.locator('#downloadLabel').textContent(),new RegExp('\\('+fullCount+' Pages\\)$'));
 const form=await p.evaluate(()=>({...StateStore.DEFAULTS,engineeringDesignNote:'Proposal-stage design: Published engineering note, verified site design before installation.',custName:'Published Export Audit',capacity:'19',moduleWattage:'500',costPerKwp:'65000',propRef:'AUDIT-PUBLISHED-019',propDate:'2026-10-04',companyName:'KTM Published QA',galleryUrl:'https://example.com/portfolio',arkaUrl:'https://example.com/layout',pvsystUrl:'https://example.com/simulation'}));
 const call=async(path,body,token)=>{const r=await fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'X-QS-Session':token}:{})},body:JSON.stringify(body)});const data=await r.json();assert.ok(r.ok,JSON.stringify(data));return data;};
 const auth=await call('auth/register',{name:'Export QA',email:'export-'+Date.now()+'@example.test',password:'AuditTest!12345',role:'owner'}),quote=await call('proposals',{form},auth.token),publication=await call('proposals/'+quote.proposal.id+'/publish',{expiresInDays:1,label:'QA'},auth.token);
 const q=await browser.newPage();q.on('pageerror',e=>errors.push(e.message));await q.goto(base+'/portal.html?t='+encodeURIComponent(publication.access.token));await q.waitForFunction(()=>document.getElementById('portalMain')&&!document.getElementById('portalMain').hidden);await q.evaluate(()=>document.fonts.ready);await q.evaluate(()=>Experience.whenReady());
 const values=await q.evaluate(()=>({name:Render.lastState.custName,capacity:Render.lastState.capacity,ref:Render.lastState.propRef,net:Finance.compute(Render.lastState).netInvestment}));assert.ok((await q.locator('#v_tsTable').textContent()).includes(form.engineeringDesignNote));assert.equal(await q.locator('#engineeringExcelHint').count(),0);assert.equal(values.name,form.custName);assert.equal(values.capacity,'19');assert.equal(values.ref,form.propRef);assert.ok(Math.abs(values.net-(19*65000*1.089-78000))<.001);assert.equal(await q.locator('#sharePrint').isEnabled(),true);
 await q.selectOption('#pdfFormat','power');await q.evaluate(()=>{window.__auditPdf=null;const Native=jspdf.jsPDF;jspdf.jsPDF=function(...args){const pdf=new Native(...args);pdf.save=name=>{window.__auditPdf={name,text:pdf.output()};};return pdf;};});await q.click('#sharePrint');await q.waitForFunction(()=>window.__auditPdf,{},{timeout:90000});const pdf=await q.evaluate(()=>__auditPdf);assert.equal((pdf.text.match(/\/Type \/Page\b/g)||[]).length,6);assert.ok(pdf.name.includes('19kWp')&&pdf.name.includes('AUDIT-PUBLISHED-019'));assert.ok(pdf.text.includes('https://example.com/portfolio'));await q.waitForFunction(()=>!document.getElementById('sharePrint').disabled);assert.equal(await q.locator('.pdf-snapshot').count(),0);
 await q.evaluate(()=>{Exporter.exportPdf=async()=>{throw new Error('QA simulated export failure');};});await q.click('#sharePrint');await q.waitForFunction(()=>document.getElementById('shareStatus').textContent==='QA simulated export failure');assert.equal(await q.locator('#sharePrint').isEnabled(),true);
 assert.deepEqual(errors,[]);console.log('PASS: format/button counts and singular labels; anonymous published portal renders saved values after fonts load; real six-page portal PDF with correct metadata/links; export failure re-enables download.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1});
