'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{chromium}=require('playwright'),pkg=require('@sparticuz/chromium'),qr=require('jsqr');
(async()=>{const b=await chromium.launch({executablePath:await(pkg.default||pkg).executablePath(),args:(pkg.default||pkg).args.filter(a=>a!=='--single-process'),headless:true});try{
 const p=await b.newPage({viewport:{width:1440,height:1200}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto((process.env.QA_BASE||'http://127.0.0.1:8080')+'/quotation.html');await p.waitForFunction(()=>window.Render?.lastState);await p.evaluate(()=>Experience.whenReady());await p.evaluate(()=>document.fonts.ready);
 async function inspect(expected){const result=await p.evaluate(async()=>{await Experience.whenReady();const page=document.querySelector('#pageProjects'),card=page.querySelector('.portfolio-link'),canvas=card?.querySelector('canvas'),foot=page.querySelector('footer').getBoundingClientRect(),rect=card?.getBoundingClientRect();return {count:page.querySelectorAll('.proj-card').length,height:page.scrollHeight,width:page.scrollWidth,fit:rect&&rect.bottom<=foot.top-4,links:[...card.querySelectorAll('a')].map(a=>a.href),qr:{width:canvas.width,height:canvas.height,data:Array.from(canvas.getContext('2d').getImageData(0,0,canvas.width,canvas.height).data)}};});assert.equal(result.count,10);assert.ok(result.height<=1124&&result.width<=794&&result.fit,JSON.stringify({...result,qr:undefined}));assert.ok(result.links.every(u=>u===expected));assert.equal(qr(new Uint8ClampedArray(result.qr.data),result.qr.width,result.qr.height)?.data,expected);}
 await inspect('https://studio.rushidhumal-04.workers.dev/gallery.html');
 await p.evaluate(()=>{galleryUrl.value='https://example.com/projects';galleryUrl.dispatchEvent(new Event('input',{bubbles:true}));});await inspect('https://example.com/projects');
 fs.mkdirSync(path.join(__dirname,'shots','portfolio-card'),{recursive:true});const image=await p.evaluate(async()=>{const canvas=await html2canvas(pageProjects,{scale:1,useCORS:true,logging:false,backgroundColor:'#fff',onclone:d=>d.body.classList.add('qs-pdf-capture')});return canvas.toDataURL();});fs.writeFileSync(path.join(__dirname,'shots','portfolio-card','projects.png'),Buffer.from(image.split(',')[1],'base64'));
 // Actual full PDF must retain both the card's QR pixels and clickable destination.
 const pdf=await p.evaluate(async()=>{const Native=jspdf.jsPDF,capture=html2canvas,result={};jspdf.jsPDF=function(...args){const pdf=new Native(...args);pdf.save=()=>{result.bytes=pdf.output('datauristring').split(',')[1];};return pdf;};window.html2canvas=async(el,opts)=>{if(el.id==='pageProjects'){const c=el.querySelector('#projectsPortfolio canvas');result.ink=c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(v=>v!==0);}return capture(el,opts);};try{await Exporter.exportPdf(()=>{},{format:'full'});return result;}finally{jspdf.jsPDF=Native;window.html2canvas=capture;}});
 const bytes=Buffer.from(pdf.bytes,'base64');assert.equal((bytes.toString('latin1').match(/\/Type \/Page\b/g)||[]).length,15);assert.ok(bytes.toString('latin1').includes('https://example.com/projects'));assert.ok(pdf.ink);fs.writeFileSync(path.join(__dirname,'shots','portfolio-card','Detailed-Proposal.pdf'),bytes);
 await p.evaluate(()=>{galleryUrl.value='javascript:alert(1)';galleryUrl.dispatchEvent(new Event('input',{bubbles:true}));});await p.evaluate(()=>Experience.whenReady());assert.equal(await p.locator('#projectsPortfolio a').count(),0);assert.deepEqual(errors,[]);
 console.log('PASS: all ten projects and portfolio card fit one A4 page; default/custom QR destinations decode, unsafe links hidden, actual 15-page PDF retains card and clickable links.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
