'use strict';
const assert=require('node:assert/strict'),{chromium}=require('playwright'),pkg=require('@sparticuz/chromium');
(async()=>{const b=await chromium.launch({executablePath:await(pkg.default||pkg).executablePath(),args:(pkg.default||pkg).args.filter(a=>a!=='--single-process'),headless:true});try{
 const c=await b.newContext(),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.QA_BASE||'http://127.0.0.1:8080';await p.goto(base+'/quotation.html');await p.waitForFunction(()=>window.Render?.lastState);
 const initial=await p.evaluate(()=>({defaultNote:StateStore.DEFAULTS.engineeringDesignNote,tech:v_tsTable.textContent,internal:engineeringReview.textContent,advanced:!!engineeringDesignNote.closest('#advancedWrap'),advisory:__qsPreflight.run().advisory}));assert.ok(initial.tech.includes(initial.defaultNote));assert.ok(!/DATA REQUIRED|per anchor|Wind pressure|Excel integration/.test(initial.tech));assert.match(initial.internal,/DATA REQUIRED/);assert.ok(initial.advanced);assert.ok(!initial.advisory.some(i=>/^DATA REQUIRED/.test(i.message)));
 const custom='Proposal-stage design: Final engineering follows site verification. <b>Customer-specific note</b> & equipment review.';
 await p.evaluate(text=>{engineeringDesignNote.value=text;engineeringDesignNote.dispatchEvent(new Event('input',{bubbles:true}));__qsSaveNow();},custom);await p.reload();await p.waitForFunction(()=>window.Render?.lastState);assert.equal(await p.inputValue('#engineeringDesignNote'),custom);assert.ok((await p.locator('#v_tsTable').textContent()).includes(custom));assert.equal(await p.locator('#v_tsTable .is-eng b').count(),0);
 const power=await p.evaluate(()=>{const h=Experience.buildPowerPages(Render.lastState),data={note:h.querySelector('.power-design-note').textContent,html:h.querySelector('.power-design-note').innerHTML,count:h.children.length,text:h.textContent};h.remove();return data;});assert.ok(power.note.includes(custom));assert.ok(!power.html.includes('<b>Customer-specific'));assert.equal(power.count,6);assert.ok(!power.text.includes('Excel integration'));
 const id=await p.evaluate(()=>Proposals.activeId());const q=await c.newPage();await q.goto(base+'/share.html?p='+encodeURIComponent(id));await q.waitForFunction(()=>window.Render?.lastState);assert.ok((await q.locator('#v_tsTable').textContent()).includes(custom));assert.equal(await q.locator('#engineeringExcelHint').count(),0);
 await p.evaluate(()=>{engineeringDesignNote.value='';engineeringDesignNote.dispatchEvent(new Event('input',{bubbles:true}));});assert.ok((await p.locator('#v_tsTable').textContent()).includes(initial.defaultNote));
 const retained=await p.evaluate(()=>{moduleLoadClassPa.value='1';moduleLoadClassPa.dispatchEvent(new Event('input',{bubbles:true}));const blocking=__qsPreflight.run().blocking;Proposals.create({...StateStore.collectForm(),custName:'Another quotation'});return {blocking,advisory:__qsPreflight.run().advisory};});assert.ok(retained.blocking.length>0,'confirmed unsafe design must still block');assert.ok(retained.advisory.some(i=>i.id==='propRef'),'duplicate-reference warning remains');assert.deepEqual(errors,[]);
 console.log('PASS: default/custom note, Advanced-only Excel reminder, persistence, HTML escaping, Detailed/Power/Customer View parity, blank fallback, internal missing-data review, retained safety blockers and duplicate-reference warnings.');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
