'use strict';
const assert=require('node:assert/strict'),{chromium}=require('playwright'),pkg=require('@sparticuz/chromium'),bundle=pkg.default||pkg;
(async()=>{const b=await chromium.launch({executablePath:await bundle.executablePath(),args:bundle.args.filter(a=>a!=='--single-process'),headless:true});try{
 const context=await b.newContext({viewport:{width:1440,height:1100}}),p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());const base=process.env.QA_BASE||'http://127.0.0.1:8080';
 await p.goto(base+'/dashboard.html');await p.waitForFunction(()=>window.PlatformAPI);
 const auth=await p.evaluate(async()=>{const r=await PlatformAPI.register('Reference QA','ref-'+Date.now()+'@example.test','ReferenceTest!123','owner');PlatformAPI.setSessionToken(r.token);return r;});
 await p.goto(base+'/dashboard.html');await p.waitForFunction(()=>document.getElementById('btnNewProposal') && !document.getElementById('btnNewProposal').disabled);await p.evaluate(()=>document.getElementById('btnNewProposal').click());
 await p.waitForURL('**/quotation.html?cloud=*');await p.waitForFunction(()=>window.CloudBridge&&!CloudBridge.isOpening()&&statusMsg.textContent.includes('Opened from cloud'));
 const initial=await p.evaluate(()=>({ref:propRef.value,id:Proposals.activeId(),cloud:CloudBridge.cloudIdFor(Proposals.activeId()),count:Proposals.list().length,pending:sessionStorage.getItem('qs.cloudOpenId')}));
 assert.match(initial.ref,/^KTM\/\d{4}\/Solar\/\d+$/);assert.equal(initial.count,1,'cloud opening creates no ghost local draft');assert.equal(initial.pending,null);
 for(let i=0;i<2;i++){await p.evaluate(id=>CloudBridge.openFromCloud(id),initial.cloud);assert.equal(await p.evaluate(()=>Proposals.list().length),1,'reopening a clean cloud quote reuses its local cache');assert.equal(await p.inputValue('#propRef'),initial.ref);}
 await p.evaluate(()=>{custName.value='Unsaved local customer';custName.dispatchEvent(new Event('input',{bubbles:true}));__qsSaveNow();});
 await p.evaluate(id=>CloudBridge.openFromCloud(id),initial.cloud);assert.equal(await p.evaluate(()=>Proposals.list().length),2);assert.ok(await p.evaluate(()=>Proposals.list().some(x=>Proposals.get(x.id).form.custName==='Unsaved local customer')),'local unsaved edits preserved');
 const previous=await p.evaluate(()=>Proposals.activeId());await p.evaluate(()=>pmNew.click());await p.waitForFunction(id=>Proposals.activeId()!==id,previous);const fresh=await p.inputValue('#propRef');assert.notEqual(fresh,initial.ref);assert.ok(!p.url().includes('cloud='),'new local draft removes stale cloud URL');
 const save=await p.evaluate(()=>CloudBridge.saveToCloud());assert.equal(save.ok,true);const cloudNew=await p.evaluate(()=>CloudBridge.cloudIdFor(Proposals.activeId()));
 await p.reload();await p.waitForFunction(()=>window.CloudBridge&&!CloudBridge.isOpening()&&statusMsg.textContent.includes('Opened from cloud'));assert.equal(await p.inputValue('#propRef'),fresh);
 const beforeVersion=await p.evaluate(()=>Proposals.activeId());await p.evaluate(()=>pmVersion.click());await p.waitForFunction(id=>Proposals.activeId()!==id,beforeVersion);assert.equal(await p.inputValue('#propRef'),fresh);assert.equal(await p.inputValue('#propVersion'),'1.1');assert.ok(!await p.evaluate(()=>__qsPreflight.run().advisory.some(x=>x.id==='propRef')),'legitimate version has no duplicate-reference warning');
 const duplicate=await p.evaluate(async id=>(await PlatformAPI.duplicateProposal(id)).proposal,cloudNew);assert.notEqual(duplicate.ref,fresh);assert.equal(duplicate.ref,duplicate.form.propRef);
 const batch=await p.evaluate(async()=>Promise.all(Array.from({length:8},async()=>{const r=await PlatformAPI.createProposal({form:{}});return r.proposal.ref;})));assert.equal(new Set(batch).size,8,'parallel local API creates get distinct references');
 const beforeDuplicate=await p.evaluate(()=>Proposals.activeId());await p.evaluate(()=>pmDup.click());await p.waitForFunction(id=>Proposals.activeId()!==id,beforeDuplicate);const uiDuplicate=await p.inputValue('#propRef');assert.ok(!batch.includes(uiDuplicate));assert.notEqual(uiDuplicate,fresh);
 // Authenticated first direct-Studio opening must use the shared counter, not local 001.
 const direct=await b.newContext(),r=await direct.newPage();await r.goto(base+'/index.html');await r.waitForFunction(()=>window.PlatformAPI);await r.evaluate(token=>PlatformAPI.setSessionToken(token),auth.token);
 await r.goto(base+'/quotation.html');await r.waitForFunction(()=>window.Proposals?.active()&&propRef.value!=='KTM/'+new Date().getFullYear()+'/Solar/001'&&Proposals.active().form.propRef===propRef.value);
 const directRef=await r.inputValue('#propRef');assert.notEqual(directRef,uiDuplicate);assert.ok(!batch.includes(directRef));r.on('dialog',d=>d.accept());await r.evaluate(()=>pmDelete.click());await r.waitForFunction(ref=>propRef.value!==ref,directRef);assert.ok(Number((await r.inputValue('#propRef')).split('/').at(-1))>Number(directRef.split('/').at(-1)));await direct.close();
 const beforeReset=await p.inputValue('#propRef');await p.evaluate(()=>resetBtn.click());assert.equal(await p.inputValue('#propRef'),beforeReset,'reset retains proposal identity');
 // Offline/unauthed browser allocation still works and deleting the last local draft creates a fresh number.
 const offline=await b.newContext(),q=await offline.newPage();q.on('dialog',d=>d.accept());await q.goto(base+'/quotation.html');await q.waitForFunction(()=>window.Render?.lastState&&window.Proposals?.active());const offRef=await q.inputValue('#propRef');assert.match(offRef,/\/001$/);
 await q.evaluate(()=>pmDelete.click());await q.waitForFunction(ref=>propRef.value!==ref,offRef);assert.match(await q.inputValue('#propRef'),/\/002$/);assert.equal(await q.evaluate(()=>Proposals.list().length),1);
 const staticContext=await b.newContext();await staticContext.route('**/api/**',route=>route.fulfill({status:404,body:'{}',contentType:'application/json'}));const staticPage=await staticContext.newPage();await staticPage.goto(base+'/quotation.html');await staticPage.waitForFunction(()=>window.Proposals?.active());const staticId=await staticPage.evaluate(()=>Proposals.activeId());await staticPage.evaluate(()=>pmNew.click());await staticPage.waitForFunction(id=>Proposals.activeId()!==id,staticId);assert.match(await staticPage.inputValue('#propRef'),/\/002$/);await staticContext.close();
 assert.deepEqual(errors,[]);console.log('PASS: Dashboard new, no ghost draft, unique refs, repeated cloud reopen deduplication, unsaved-local preservation, Studio New/save/reload, immutable version, cloud duplicate, concurrent API creates, reset identity and last-draft deletion.');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
