/* Rebuilt storage catalogue, optional systems and standalone document lifecycle. */
'use strict';
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),puppeteer=require('puppeteer-core');
let passed=0;const check=(n,c)=>{assert(c,n);passed++;console.log('  ✓ '+n);};
(async()=>{
 const {default:chromium}=await import('@sparticuz/chromium');const browser=await puppeteer.launch({executablePath:await chromium.executablePath(),args:chromium.args.filter(x=>x!=='--single-process'),headless:true});
 try{
  const page=await browser.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});page.on('dialog',d=>d.accept());
  const base=process.env.QA_BASE||'http://127.0.0.1:8080';await page.setViewport({width:1440,height:1200});await page.goto(base+'/quotation.html',{waitUntil:'networkidle0'});await page.evaluate(()=>document.fonts.ready);
  const original=await page.evaluate(()=>({finance:JSON.stringify(Finance.compute(Render.lastState)),form:StateStore.collectForm()}));
  const apply=values=>page.evaluate(v=>{StateStore.applyForm(v);Render.renderAll();},values);
  async function geometry(label,p=page){const bad=await p.evaluate(()=>[...document.querySelectorAll('.bess-page,.system-page')].filter(e=>e.checkVisibility()).flatMap(e=>{const footer=e.querySelector('.pg-foot').getBoundingClientRect().top;return [...e.querySelector('.pg-body').children].filter(c=>c.getBoundingClientRect().bottom>footer-2).map(c=>e.id+': '+c.className).concat(e.scrollHeight>1124?[e.id+' overflow']:[]);}));check(label+' fits its A4 pages: '+bad.join(', '),bad.length===0);}
  check('both supplements default off with fifteen visible pages',await page.evaluate(()=>!bessEnabled.checked&&!systemEnabled.checked&&Render.lastVisible.length===15));
  check('backup duration starts blank rather than inventing a customer requirement',await page.evaluate(()=>bessTargetHours.value===''));
  check('standalone formats are disabled until their feature is enabled',await page.$eval('#pdfFormat',e=>['bess','system','system-power'].every(v=>e.querySelector('option[value="'+v+'"]').disabled)));
  check('five battery models plus Custom last, with custom entry underneath',await page.evaluate(()=>bessModel.options.length===7&&bessModel.options[6].value==='custom'&&!!bessCustomIdentity.querySelector('#bessMake')));
  await page.evaluate(()=>{document.querySelector('[data-section=bessEnabled]').open=true;document.querySelector('[data-bess-choice=yes]').click();});await page.select('#bessModel','pylon-us5000');
  check('model selection immediately calculates and displays a 9.6 kWh bank',await page.evaluate(()=>bessCapacity.value==='9.6'&&bessUnits.value==='2'&&bessPower.value==='7'&&bessDischargeEff.value==='96'&&bessOverviewBody.textContent.includes('9.6 kWh')));
  check('automatic derived inputs are readonly and source/assumption provenance is visible',await page.evaluate(()=>bessCapacity.readOnly&&bessDod.readOnly&&bessPower.readOnly&&bessCatalogueSource.textContent.includes('OEM')&&bessAssessmentBody.textContent.includes('design assumptions')));
  await apply({capacity:'10'});check('changing solar quotation resizes the automatic battery bank',await page.evaluate(()=>bessUnits.value==='3'&&bessCapacity.value==='14.4'));
  await apply({capacity:'7',bessSizing:'backup',bessLoad:'2',bessTargetHours:'4'});check('essential load × hours updates the target without solar-load guessing',await page.evaluate(()=>Bess.sizing(Render.lastState,Finance.compute(Render.lastState)).target===8&&bessUnits.value==='2'));
  await apply({bessPcsKw:'1'});check('undersized converter is flagged and cannot establish backup',await page.evaluate(()=>bessSizingStatus.textContent.includes('below')&&Bess.compute(Render.lastState,Finance.compute(Render.lastState)).backupHours===null));
  await apply({bessPcsKw:'5',bessBackupReady:'pending'});await apply({bessBackupReady:'yes',bessInverter:'Verified project hybrid inverter',bessCoupling:'dc'});check('explicit confirmed configuration establishes conditional runtime',await page.evaluate(()=>Bess.compute(Render.lastState,Finance.compute(Render.lastState)).backupHours>0));
  await apply({bessCost:'300000'});
  await page.$eval('#bessInverter',e=>{e.value='Another reviewed inverter';e.dispatchEvent(new Event('input',{bubbles:true}));});
  check('editing the inverter immediately invalidates engineering confirmation',await page.evaluate(()=>bessBackupReady.value==='pending'));
  await apply({bessBackupReady:'yes'});await page.select('#bessCoupling','ac');
  check('editing coupling also invalidates engineering confirmation',await page.evaluate(()=>bessBackupReady.value==='pending'));
  await apply({bessUnitsOverride:'3'});
  check('automatic bank changes clear stale installed price in form and live state',await page.evaluate(()=>bessCost.value===''&&Render.lastState.bessCost===''));
check('changing the automatic bank invalidates prior engineering confirmation',await page.evaluate(()=>bessBackupReady.value==='pending'&&Render.lastState.bessBackupReady==='pending'));
  await page.select('#bessSpecMode','manual');await apply({bessCapacity:'18',bessPower:'4'});check('manual override does not silently snap back to catalogue ratings',await page.evaluate(()=>bessCapacity.value==='18'&&!bessCapacity.readOnly&&Render.lastState.bessCapacity==='18'));
  await apply({bessBackupReady:'yes',bessCost:'300000'});await page.$eval('#bessPower',e=>{e.value='3.5';e.dispatchEvent(new Event('input',{bubbles:true}));});check('manual electrical-rating edits also invalidate prior backup confirmation and price',await page.evaluate(()=>bessBackupReady.value==='pending'&&bessCost.value===''));
  await apply({bessCost:'123000',bessWarranty:'Previous model warranty',bessBackupReady:'yes'});
  await page.select('#bessModel','custom');
  check('switching to Custom clears the old model price, warranty and confirmation',await page.evaluate(()=>bessCost.value===''&&bessWarranty.value===''&&bessBackupReady.value==='pending'));
await apply({bessMake:'Customer specified storage <not markup>'});check('Custom reveals manual entry and preserves literal text',await page.evaluate(()=>!bessCustomIdentity.hidden&&bessOverviewBody.textContent.includes('<not markup>')&&!bessOverviewBody.querySelector('not')));
  for(const id of ['pylon-us2000c','pylon-us3000c','dyness-dl50c','deye-seg51','pylon-us5000']){await page.select('#bessModel',id);check(id+' fills model-specific specifications without inventing an installed price',await page.evaluate(id=>bessMake.value===StorageCatalog.get(id).name&&Number(bessCapacity.value)>0&&bessCost.value==='',id));}
  for(const reason of ['requested','recommended','alternative']){await page.select('#bessReason',reason);check(reason+' is reflected in the report',await page.evaluate(()=>bessOverviewBody.textContent.includes(Bess.reason(Render.lastState))));}
  await apply({bessInclude:false});check('standalone-only BESS stays enabled but leaves solar page count at fifteen',await page.evaluate(()=>bessEnabled.checked&&Render.lastVisible.length===15&&!document.getElementById('pageBessOverview').checkVisibility()&&!v_exSub.textContent.includes('battery')));
  check('standalone BESS download stays available when not included in main proposal',await page.$eval('#pdfFormat option[value=bess]',e=>!e.disabled));
  await apply({bessInclude:true,bessUseCase:'self',bessCost:'300000'});await page.evaluate(()=>bessUseQuote.click());
  check('quotation-linked economics fills explicit editable starting assumptions',await page.evaluate(()=>bessAutoEconomics.checked&&bessSourceEnergy.value==='8.4'&&bessImportRate.value==='15'&&bessRte.value==='88'&&bessSourceRate.value===''&&bessOm.value===''));
  check('missing opportunity cost and O&M still withhold financial benefit',await page.evaluate(()=>Bess.compute(Render.lastState,Finance.compute(Render.lastState)).annualBenefit===null));
  await apply({bessSourceRate:'3',bessOm:'2000'});check('complete economic assumptions calculate a finite separate benefit',await page.evaluate(()=>Number.isFinite(Bess.compute(Render.lastState,Finance.compute(Render.lastState)).annualBenefit)));
  await geometry('Automatic battery with financial illustration');
  check('linked economic fields are visibly read-only until unlinked',await page.evaluate(()=>bessSourceEnergy.readOnly&&bessDemand.readOnly&&bessImportRate.readOnly));
  await apply({bessAutoEconomics:false});check('manual economics can override the quotation link',await page.evaluate(()=>!bessSourceEnergy.readOnly&&!bessDemand.readOnly&&!bessImportRate.readOnly));
  await apply({bessAutoEconomics:true,bessSizing:'solar',bessReserve:'20'});
  check('solar energy shifting accounts for reserve in automatic module count and report',await page.evaluate(()=>bessUnits.value==='3'&&bessOverviewBody.textContent.includes('20% operating reserve included')));
  await geometry('Automatic reserve-aware financial report');
  await apply({bessUnitsOverride:'2'});check('manual quantity below reserve-adjusted target is flagged',await page.evaluate(()=>bessSizingStatus.textContent.includes('after operating reserve')));
  await apply({bessUnitsOverride:'',bessSizing:'backup'});await apply({bessCost:'300000'});

  await page.evaluate(()=>{document.querySelector('[data-section=systemEnabled]').open=true;document.querySelector('[data-system-choice=yes]').click();});
  check('five system templates and Custom last',await page.evaluate(()=>systemTemplate.options.length===6&&systemTemplate.options[5].value==='custom'));
  for(const kind of ['zero','monitoring','ev','pfc','dg']){await page.select('#systemTemplate',kind);check(kind+' fills connected editable information without a price',await page.evaluate(()=>systemName.value&&systemPurpose.value&&systemScope.value&&systemNotes.value&&systemPrice.value===''&&systemOverviewBody.textContent.includes(systemName.value)));await geometry(kind+' template');}
  await page.select('#systemTemplate','custom');await apply({systemName:'Load prioritisation study',systemPurpose:'Assess essential circuits for the selected project.',systemEquipment:'Site metering\nReview of existing control panel',systemScope:'Review the customer load schedule\nPrepare an agreed commissioning plan',systemNotes:'Custom scope, not an automatic savings calculation.',systemExclusions:'Equipment supply unless separately priced',systemPrice:'25000'});
  check('Custom system edits appear literally on both pages',await page.evaluate(()=>!systemCustomName.hidden&&systemOverviewBody.textContent.includes('Load prioritisation study')&&systemDetailBody.textContent.includes('Custom scope, not an automatic savings calculation.')));
  check('additional-system price is separate and solar Finance remains unchanged',await page.evaluate(v=>systemOverviewBody.textContent.includes('25,000')&&JSON.stringify(Finance.compute(Render.lastState))===v,original.finance));
  await apply({systemWarranty:'Prior system warranty',systemDelivery:'Prior system delivery'});await page.select('#systemTemplate','zero');check('template change clears stale price, warranty and delivery while refreshing technical notes',await page.evaluate(()=>systemPrice.value===''&&systemWarranty.value===''&&systemDelivery.value===''&&systemNotes.value.includes('transient export')));await apply({systemPrice:'25000'});
  check('main proposal and multilingual briefing disclose additional scope',await page.evaluate(()=>v_exSub.textContent.includes('system supplement')&&v_svSub.textContent.includes('not modelled')&&v_inPayNote.textContent.includes('Solar-only')&&v_finSub.textContent.includes('Solar-only')&&v_opSub.textContent.includes('Solar-only')&&Briefing.scriptFor(Render.lastState,'en').join(' ').includes('additional system')));
  check('optional recommendations are not authorised by inclusion alone',await page.evaluate(()=>v_clAcceptIntro.textContent.includes('does not authorise')));
  await apply({systemInclude:'false',bessInclude:'false',bessAutoEconomics:'false'});
  check('imported string flags cannot silently enable optional scope',await page.evaluate(()=>!systemInclude.checked&&!bessInclude.checked&&!bessAutoEconomics.checked));
  await apply({bessAutoEconomics:true});
  await apply({systemInclude:false,bessInclude:false});check('both standalone supplements can be prepared without changing main page count',await page.evaluate(()=>Render.lastVisible.length===15));
  await page.evaluate(()=>__qsSaveNow());const id=await page.evaluate(()=>Proposals.activeId());await page.reload({waitUntil:'networkidle0'});
  check('reload preserves catalogue, mode, calculated fields, custom scope and independent inclusion',await page.evaluate(()=>bessModel.value==='pylon-us5000'&&bessSpecMode.value==='auto'&&bessEnabled.checked&&!bessInclude.checked&&systemEnabled.checked&&!systemInclude.checked&&systemPrice.value==='25000'&&bessAutoEconomics.checked));
  const customer=await browser.newPage();customer.on('pageerror',e=>errors.push(e.message));await customer.goto(base+'/share.html?p='+id,{waitUntil:'networkidle0'});check('Customer View has the same fifteen main pages and standalone formats',await customer.evaluate(()=>Render.lastVisible.length===15&&!pdfFormat.querySelector('[value=bess]').disabled&&!pdfFormat.querySelector('[value=system]').disabled));
  await page.evaluate(()=>document.getElementById('pmDup').click());check('duplicate retains both optional reports',await page.evaluate(()=>Proposals.active().form.systemTemplate==='zero'&&Proposals.active().form.bessModel==='pylon-us5000'));
  const output=path.join(__dirname,'shots','supplements');fs.mkdirSync(output,{recursive:true});for(const f of fs.readdirSync(output))if(/\.(pdf|json)$/.test(f))fs.unlinkSync(path.join(output,f));
  const cdp=await page.createCDPSession();await cdp.send('Browser.setDownloadBehavior',{behavior:'allow',downloadPath:output,eventsEnabled:true});
  async function download(action){let name,timer;const promise=new Promise((resolve,reject)=>{timer=setTimeout(()=>reject(new Error('download timeout')),180000);cdp.once('Browser.downloadWillBegin',e=>name=e.suggestedFilename);const on=e=>{if(e.state==='completed'||e.state==='canceled'){cdp.off('Browser.downloadProgress',on);clearTimeout(timer);e.state==='completed'?resolve():reject(new Error('download canceled'));}};cdp.on('Browser.downloadProgress',on);});promise.catch(()=>{});try{await action();await promise;return path.join(output,name);}finally{clearTimeout(timer);}}
  const json=await download(()=>page.evaluate(()=>document.getElementById('exportBtn').click()));const payload=JSON.parse(fs.readFileSync(json));check('actual JSON backup contains both supplement modes and catalogue identity',payload.proposal.form.bessModel==='pylon-us5000'&&payload.proposal.form.systemEnabled&&payload.proposal.form.systemInclude===false);
  await page.evaluate(()=>document.getElementById('pmNew').click());check('New clears both reports without inherited catalogue selections',await page.evaluate(()=>!bessEnabled.checked&&!systemEnabled.checked&&bessModel.value===''&&systemPrice.value===''));
  const newId=await page.evaluate(()=>Proposals.activeId());await(await page.$('#importFile')).uploadFile(json);await page.waitForFunction(id=>Proposals.activeId()!==id,{},newId);check('actual JSON import restores standalone reports and automatic sizing',await page.evaluate(()=>bessEnabled.checked&&systemEnabled.checked&&bessModel.value==='pylon-us5000'&&bessSpecMode.value==='auto'&&Render.lastVisible.length===15));
  await page.evaluate(()=>{window.__nativeCapture=html2canvas;window.__supplementCaptures=[];window.__supplementProofs={};window.__supplementFooters=[];window.html2canvas=async(el,opts)=>{const c=await __nativeCapture(el,opts);__supplementCaptures.push(el.id);__supplementFooters.push(el.querySelector('.pf-right')?.textContent||'power');if(el.classList.contains('bess-page')||el.classList.contains('system-page'))__supplementProofs[el.id]=c.toDataURL('image/png');if(el.id==='pageBessOverview'){const r=el.querySelector('.sp-flow-line svg').getBoundingClientRect(),p=el.getBoundingClientRect(),scale=c.width/p.width,d=c.getContext('2d').getImageData(Math.round((r.left-p.left)*scale),Math.round((r.top-p.top)*scale),Math.round(r.width*scale),Math.round(r.height*scale)).data;let ink=0;for(let i=0;i<d.length;i+=4)if(d[i]>120&&d[i]<230&&d[i+1]>60&&d[i+1]<170&&d[i+2]<120)ink++;window.__flowInk=ink;}return c;};});
  for(const [format,count] of [['bess',2],['system',2],['system-power',1]]){
   await page.evaluate(()=>{__supplementCaptures=[];__supplementFooters=[];});const file=await download(()=>page.evaluate(format=>Exporter.exportPdf(()=>{}, {format}),format));
   check('actual '+format+' PDF has '+count+' correctly numbered pages',(fs.readFileSync(file,'latin1').match(/\/Type \/Page\b/g)||[]).length===count&&await page.evaluate(n=>__supplementFooters.every((t,i)=>t==='Page '+(i+1)+' of '+n),count));
   if(format==='bess')check('new battery flow icons are actually visible in the PDF raster',await page.evaluate(()=>__flowInk>20));
  }
  await apply({bessInclude:true,systemInclude:true,customerType:'commercial',monthlyBill:'50000',loanAmt:'500000',loanRate:'9',loanYears:'10',bomModules:'300000',bomInverter:'100000',bomStructure:'50000',bomBos:'50000',bomInstall:'50000',bomLiaison:'20000',availableArea:'200',arkaUrl:'https://example.com/layout',pvsystUrl:'https://example.com/report'});
  await page.evaluate(()=>{window.__qsOptions=[{id:'a',name:'Solar A',fields:{capacity:'7'}},{id:'b',name:'Solar B',fields:{capacity:'10'}}];Render.renderAll();});
  check('all optional content gives twenty-one correctly ordered main pages',await page.evaluate(()=>Render.lastVisible.length===21&&downloadLabel.textContent.includes('21')));await geometry('All optional content');await page.emulateMediaType('print');await geometry('Printed reports');await page.emulateMediaType('screen');
  const full=await download(()=>page.evaluate(()=>Exporter.exportPdf(()=>{}, {format:'full'})));check('actual full PDF contains twenty-one pages',(fs.readFileSync(full,'latin1').match(/\/Type \/Page\b/g)||[]).length===21);
  const power=await download(()=>page.evaluate(()=>Exporter.exportPdf(()=>{}, {format:'power'})));check('combined concise Power Proposal still fits two pages',(fs.readFileSync(power,'latin1').match(/\/Type \/Page\b/g)||[]).length===2);
  const proofs=await page.evaluate(()=>__supplementProofs);for(const [id,img] of Object.entries(proofs))fs.writeFileSync(path.join(output,id+'.png'),Buffer.from(img.split(',')[1],'base64'));
  await page.evaluate(()=>__qsSaveNow());await customer.goto(base+'/share.html?p='+await page.evaluate(()=>Proposals.activeId()),{waitUntil:'networkidle0'});check('Customer View included reports match builder calculations and scope',await customer.evaluate(()=>Render.lastVisible.length===21&&bessOverviewBody.textContent.includes('Pylontech US5000')&&systemOverviewBody.textContent.includes('Zero Export Control')));await geometry('Customer View',customer);
  await page.setViewport({width:390,height:844});await page.$eval('[data-section=bessEnabled]',e=>e.open=true);check('mobile form and document avoid horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await geometry('Mobile A4');
  await page.evaluate(()=>{document.querySelector('[data-section=bessEnabled]').scrollIntoView({behavior:'instant'});});await page.screenshot({path:path.join(output,'controls-mobile.png')});
  await page.setViewport({width:1440,height:1200});await apply({systemScope:'Extremely long custom scope text '.repeat(350)});
  const error=await page.evaluate(async()=>{try{await Exporter.exportPdf(()=>{},{format:'system'});return '';}catch(e){return e.message;}});check('overlong scope fails explicitly instead of issuing clipped PDF',error.includes('exceeds the page'));
  await apply({systemEnabled:false,bessEnabled:false});check('disabling reports removes pages and disables all independent format choices',await page.evaluate(()=>!document.getElementById('pageSystemOverview').checkVisibility()&&pdfFormat.querySelector('[value=bess]').disabled&&pdfFormat.querySelector('[value=system]').disabled));
  const disabled=await page.evaluate(async()=>{try{await Exporter.exportPdf(()=>{},{format:'bess'});return false;}catch(e){return e.message.includes('Enable BESS');}});check('disabled BESS cannot be exported through API',disabled);
  await page.evaluate(()=>{window.__qsOptions=[];document.getElementById('resetBtn').click();});check('Reset clears additional-system text, price and battery model',await page.evaluate(()=>!systemEnabled.checked&&systemScope.value===''&&systemPrice.value===''&&bessModel.value===''&&Render.lastVisible.length===15));
  check('no runtime or console errors: '+errors.join('; '),errors.length===0);console.log(`\n${passed} passed, 0 failed`);
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
